In [6]:
import torch

a = torch.empty(size=(6,1))
-9e15*torch.ones_like(a)

tensor([[-9.0000e+15],
        [-9.0000e+15],
        [-9.0000e+15],
        [-9.0000e+15],
        [-9.0000e+15],
        [-9.0000e+15]])

In [4]:
import torch

a = torch.Tensor([
    [1,2],
    [3,4],
    [5,6]
])

# print(a.repeat(1,3)) #第0维大小乘以1（不变）；第1维大小乘以3（重复三遍）
h1 = a.repeat(1,3).view(3*3,-1)
# print(h1)
h2 = a.repeat(3,1)
# print(h2)
# print(torch.cat([h1,h2], dim=1))
h = torch.cat([h1,h2], dim=1).view(3,-1,4) #每个节点分别与其它节点（包括当前节点自身）特征拼接
print(h)
a = torch.Tensor([0.1,0.1,0.1,0.1]).view(4,1)
result = torch.matmul(h,a)
print(result)
print(result.squeeze())

#以下操作效果一样
# h = torch.cat([h1,h2], dim=1) #每个节点分别与其它节点（包括当前节点自身）特征拼接
# result = torch.matmul(h,a)
# print(result.view(3,3))

tensor([[[1., 2., 1., 2.],
         [1., 2., 3., 4.],
         [1., 2., 5., 6.]],

        [[3., 4., 1., 2.],
         [3., 4., 3., 4.],
         [3., 4., 5., 6.]],

        [[5., 6., 1., 2.],
         [5., 6., 3., 4.],
         [5., 6., 5., 6.]]])
tensor([[[0.6000],
         [1.0000],
         [1.4000]],

        [[1.0000],
         [1.4000],
         [1.8000]],

        [[1.4000],
         [1.8000],
         [2.2000]]])
tensor([[0.6000, 1.0000, 1.4000],
        [1.0000, 1.4000, 1.8000],
        [1.4000, 1.8000, 2.2000]])
tensor([[0.6000, 1.0000, 1.4000],
        [1.0000, 1.4000, 1.8000],
        [1.4000, 1.8000, 2.2000]])


In [12]:
import torch

a = [
    torch.Tensor([
        [1,1,1],
        [2,2,2]
    ]),
    torch.Tensor([
        [3,3,3],
        [4,4,4]
    ]),
    torch.Tensor([
        [5,5,5],
        [6,6,6]
    ])
]

torch.cat(a,dim=1)

tensor([[1., 1., 1., 3., 3., 3., 5., 5., 5.],
        [2., 2., 2., 4., 4., 4., 6., 6., 6.]])